server:
  name: "api"
  host: "localhost"
  grpc:
    port: ":50050"
  http:
    port: ":8080"
  metrics:
    port: ":9050"
database:
  driver: "postgres"
  host: "127.0.0.1"
  port: ":5432"
  user: "postgres"
  password: "postgres"
  name: "postgres"
jwt:
  secret: "secret"
  expires: "60m"
redis:
  host: "localhost"
  port: ":6379"
  password: ""
  cache_duration: "60m"
kafka:
  host: "127.0.0.1"
  port: ":9092"
  user: "kafka"
  password: ""
  is_remote: false
  kafka_config:
    brokers: [ "127.0.0.1:9093" ]
    groupID: microservice_consumer
    initTopics: true
  publisher_config:
    topic: event_created
    topicPrefix: eventstore
    partitions: 10
    replicationFactor: 1
  topic_config:
    eventCreated:
      topicName: event_created
      partitions: 10
      replicationFactor: 1
s3:
  secret_key: "minio"
  access_key: "minio123"
  region: "us-east-1"
  public_bucket_name: "public_bucket"
  private_bucket_name: "private_bucket"
  endpoint: "http://127.0.0.1:9000"
  public_url: "http://127.0.0.1/s3"
  pre_sign_url_duration: 30
mail:
  driver: "smtp"
  host: "smtp.mailtrap.io"
  port: ":2525"
  username: "a824c848c8df5d"
  password: "123456"
  encryption: ""