server:
  name: "api"
  host: "localhost"
  grpc:
    port: ":50050"
  http:
    port: ":8080"
  metrics:
    port: ":9050"
    basePath: "/metrics"
    ignoreLogUrls: [ "metrics", "swagger" ]
database:
  driver: "postgres"
  host: "localhost"
  port: ":5432"
  user: "postgres"
  password: "postgres"
  name: "postgres"
cassandra:
  hostPort: [ "localhost:9043" ]
  user: "cassandra"
  password: "cassandra"
  keyspace: "test_keyspace"
elastic:
  addresses: ["http://localhost:9200"]
  username: ""
  password: ""
  apiKey: ""
  enableLogging: false
jwt:
  secret: "secret"
  expires: "60m"
redis:
  host: "localhost"
  port: ":6379"
  password: ""
  cacheDuration: "60m"
kafka:
  host: "localhost"
  port: ":9092"
  user: "kafka"
  password: ""
  isRemote: false
  kafkaConfig:
    brokers: [ "localhost:9093" ]
    groupID: microservice_consumer
    initTopics: true
  publisherConfig:
    topic: event_created
    topicPrefix: eventstore
    partitions: 10
    replicationFactor: 1
  topicConfig:
    eventCreated:
      topicName: event_created
      partitions: 10
      replicationFactor: 1
eventSource:
  SnapshotFrequency: 5
jaeger:
  enable: false
  serviceName: jaeger_service
  host: "localhost"
  port: ":6831"
  logSpans: false
s3:
  secretKey: "minio"
  accessKey: "minio123"
  region: "us-east-1"
  publicBucketName: "publicBucket"
  privateBucketName: "privateBucket"
  endpoint: "http://localhost:9000"
  publicUrl: "http://localhost/s3"
  preSignUrlDuration: 30
mail:
  driver: "smtp"
  host: "smtp.mailtrap.io"
  port: ":2525"
  username: "a824c848c8df5d"
  password: "123456"
  encryption: ""